# to replace the values in content 
#but file format must be file.js (jinja2 template)
# in ex:file this is {{ value}} it will replece in copy moduel
# it pass the dynamic content in template 
#in master create a file.j2
- hosts: all
  become: yes
  vars:
   package: anything  
  tasks:
  - name:
    template: 
     src: /home/file.j2 # we rename the file or same file it will copy in node.
                       # if not mentioned the filename in dest paramenter it copy the file.j2 in node.
     dest: /home/file
    
